services:
  ollama:
    image: ollama/ollama
    container_name: ollama_v3
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      - ollama
    volumes:
      - .:/app
    working_dir: /app
    command: ["poetry", "run", "python", "main.py", "--config", "./default.yaml"]
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_bot
    depends_on:
      - app
    volumes:
      - .:/bot
    working_dir: /bot
    command: [ "poetry", "run", "python", "bot.py", "--config", "./default.yaml" ]
    restart: unless-stopped

volumes:
  ollama: